### ISSUE TITLE
Add some training exercises

### ISSUE THREAD

**Issue by paf31** [sharkdp/cube-composer#18]
Great game! Just a suggestion - a few very basic examples, maybe with one step each, just to illustrate the purpose of each function, would probably be very useful.

**Comment by sharkdp** [comment]
:+1: Also has been mentioned [here](https://news.ycombinator.com/item?id=9644324) a few times. I will work on this.

**Comment by sharkdp** [comment]
Added a "chapter 0" with three training exercises... and more to come in the future
