### ISSUE TITLE
General UI improvements

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/cube-composer#19]
See discussion here: https://news.ycombinator.com/item?id=9644324
- [x] "white as a catchall is a bit misleading. Perhaps a different border color or an asterisk inside the square to clearly mark that it's not an actual white block?"
- [x] stack(X) instead of push(X)?
- [x] Replace 'press R to reset' by a button (the rest of the game is mouse-driven)
- [x] In a transformer like Y -> BB, the two B's could be stacked on top of each other
- [x] Bigger "Solved!" message... render something on the canvas?
- [x] "Play next level" button, once it is finished
- [x] Highlight the 'goal' / target (border around, "Make the left image look like the right image.", etc.)

**Comment by refset** [comment]
Been thinking about this game a lot lately :)
- why 3D and not 2D?
- show resulting shape as well as function description

**Comment by sharkdp** [comment]
Thanks for your comment!

> why 3D and not 2D?

Hm.. mainly because I really like the Isomer-type graphics :smile:. The cube matrices/walls are two-dimensional and the third axis corresponds to a (discrete) timeline, showing the transformation steps. We could also show the cubes in the 2D canvas plane and arrange multiple steps side by side... what would be the advantages? Or what do you have in mind?

> show resulting shape as well as function description

I am not sure what you mean?

**Comment by refset** [comment]
Thanks for explaining the reasons for 3d, but I think 2d is a simpler representation to process. Perhaps 3d (with x-ray, and full rotation) will be useful for a nested map visualisation ;)

This is what I am imagining: https://github.com/jez0990/cube-composer/blob/master/design-idea.svg

...I'd love to know what you think!

**Comment by sharkdp** [comment]
> Thanks for explaining the reasons for 3d, but I think 2d is a simpler representation to process. Perhaps 3d (with x-ray, and full rotation) will be useful for a nested map visualisation ;)
> 
> This is what I am imagining: https://github.com/jez0990/cube-composer/blob/master/design-idea.svg

Sorry, it's been a long time... just commenting here for the sake of completeness. After our private discussion (June 22nd), I see some of the advantages of your approach. Generally though, I still like the 3D interface better. I'm closing this for now. Thanks again for the discussion!

**Comment by refset** [comment]
Cool, I appreciate the update and I'm very glad you're still working on this. I haven't lost interest in helping, I've just gotten rather side-tracked lately! I hope to dive into purescript properly and collaborate again soon.
