### ISSUE TITLE
Better explanation/name for stackEqual

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/cube-composer#20]
See comments here: https://news.ycombinator.com/item?id=9644324

Could also be introduced by an introductory level, see #18.

**Comment by hickford** [comment]
I was confused for a long while. It helped me to think "stack _columns_ that are equal and adjacent". The other functions are all block based.

**Comment by hickford** [comment]
Really cool game, original mechanic. 

Zachtronics (Spacechem) would love this.

**Comment by hickford** [comment]
You could show a verbal description in a tooltip

```
<li id="stackEqual" title="stack columns that are equal and adjacent">stackEqual</li>
```

**Comment by sharkdp** [comment]
> I was confused for a long while. It helped me to think "stack columns that are equal and adjacent". The other functions are all block based.

Several others have also mentioned this. I should clearly explain it somewhere in an introductory level. Please note that the other functions in the "1.x" levels are of the form `map f`, where `f` is some function that operates on a single stack. The `map` part indicates that these functions will be run for each stack. `stackEqual`, however, operates on a higher dimension (If you think of the matrices/walls of cubes in the game as two dimensional arrays).

> You could show a verbal description in a tooltip
> 
> <li id="stackEqual" title="stack columns that are equal and adjacent">stackEqual</li>

Great idea! :+1:
I also like your description.

> Really cool game, original mechanic.

Thanks!

**Comment by sharkdp** [comment]
Closed this for now, `stackEqualColumns` will be better explained in the introductory levels (see #18)
