### ISSUE TITLE
Support smaller screen sizes

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/cube-composer#25]

**Comment by hemanth** [comment]
You meant this?

![screen shot 2015-09-14 at 01 21 57](https://cloud.githubusercontent.com/assets/18315/9838587/16abe970-5a7f-11e5-8942-831a3e9a91b7.png)

**Comment by sharkdp** [comment]
Well... I think your screenshot mainly documents another issue which is rather related to #22. I was thinking about solving this with an adaptive spacing between the different steps (spacing between walls further to the left could be smaller).

This issue is rather about a problem with small screen sizes where the content does not fit in the browser window (horizontally).

**Comment by hemanth** [comment]
:+1:
