### ISSUE TITLE
Show function applications next to results

### ISSUE THREAD

**Issue by thSoft** [sharkdp/cube-composer#27]
IMHO it would be better if each functions application appeared between its input and output. Is the current layout intentional?

**Comment by sharkdp** [comment]
That would probably be ideal, yes. I couldn't come up with good design that fits in a small space, though. Do you have a specific layout in mind? (see also idea by jez0990 here: #19)

**Comment by thSoft** [comment]
I thought of simply interleaving the results with the function applications vertically.
Or there some layouts among Bret Victor's ideas:
- http://worrydream.com/MediaForThinkingTheUnthinkable/ - Demo 5 (Nile)
- http://worrydream.com/substroke/

Yes, https://github.com/sharkdp/cube-composer/issues/19#issuecomment-113578972 seems pretty much the same, so you can mark this as duplicate. :)

**Comment by sharkdp** [comment]
Thank you for the feedback and the links!
