### ISSUE TITLE
Mobile version using ReactNative

### ISSUE THREAD

**Issue by texastoland** [sharkdp/cube-composer#28]
Any interest in marketing this? Selfishly I wanna play on my phone 😹

https://github.com/nicholaskariniemi/purescript-react-native

**Comment by paf31** [comment]
:fireworks: :+1: Yes, please.

**Comment by texastoland** [comment]
I'm interested (depending on availability) in helping out!

**Comment by paf31** [comment]
I'd help out as best I can. Having a PureScript app on the app store would be amazing :smile:

**Comment by sharkdp** [comment]
With some help, I would definitely be interested in doing this!

(Unfortunately) the main issue I see is with the design / UX. I had a hard time supporting small (tablet) screen sizes already. I'm pretty sure that the UI would need a completely new concept for phones.

Apart from that, I had plans to replace the low-level purescript-dom code with purescript-thermite anyway. So this would be a good motivation (would Thermite work with react-native?).

Another thing I would like to finish first is replacing Isomer.js with purescript-isometric (that's almost done), which get's rid of a lot of ugly FFI bindings.

**Comment by texastoland** [comment]
Okay go ahead and finish Isomer, start on Thermite, I can make a wireframe for responsive layout and mobile interactions, and reconvene after LambdaConf (I'll have less on my plate) 🎊

**Comment by paf31** [comment]
Thermite should play nicely with React Native. I've got a demo of `purescript-react` and React Native somewhere. And there is `purescript-react-native` too. The components are different, but the underlying abstraction should work fine.

I imagine there would be quite a lot of work needed to build out the native components first.

**Comment by texastoland** [comment]
> I imagine there would be quite a lot of work needed to build out the native components first.

It's been a little while but I have iOS experience.

**Comment by paf31** [comment]
Well, I was just thinking of wrapping the ones provided by the React Native API using the FFI.

**Comment by sharkdp** [comment]
That sounds good! @paf31: what do you mean by building out the native components?

Edit: Okay, I see.

**Comment by texastoland** [comment]
I linked Futurice's experimental bindings in the description (albeit potentially naive).

**Comment by connecttobn** [comment]
<img width="601" alt="screen shot 2016-08-30 at 3 41 27 pm" src="https://cloud.githubusercontent.com/assets/715128/18085357/7302f43a-6ec8-11e6-9598-5dc03d6669fb.png">

**Comment by connecttobn** [comment]
I am **not a designer** but I think cool to bring it on mobile!

**Comment by sharkdp** [comment]
@connecttobn This actually includes some neat ideas. I'm quite sure that the target image will be too small, though..

There are also some ideas here: https://github.com/sharkdp/cube-composer/issues/19

**Comment by saketh-kowtha** [comment]
hello friends 
i am new to purescript i want to learn purescript i dosent found any proper tutorial on it can anyone send me references to became expert in purescript

**Comment by sharkdp** [comment]
@saketh-kowtha http://www.purescript.org/ should have all the references you need to get started.

**Comment by saketh-kowtha** [comment]
Hello David Peter I want References on Canvas especially on rotation of object

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sharkdp** [comment]
> Hello David Peter I want References on Canvas especially on rotation of object

Take a look at https://pursuit.purescript.org/packages/purescript-canvas/
