### ISSUE TITLE
License for the repository?

### ISSUE THREAD

**Issue by bitemyapp** [sharkdp/cube-composer#29]
I love this project, but at present it has no license. Could one be added please?

**Comment by jocelyn-stericker** [comment]
Note: I'm not the maintainer.

The license seems to be MIT:
- https://github.com/sharkdp/cube-composer/blob/a64c89809cdbbd0e8aef41ead8324e5ca7a7cb53/LICENSE
- https://github.com/sharkdp/cube-composer/blob/a64c89809cdbbd0e8aef41ead8324e5ca7a7cb53/package.json#L9
- https://github.com/sharkdp/cube-composer/blob/a64c89809cdbbd0e8aef41ead8324e5ca7a7cb53/bower.json#L8

**Comment by TJScalzo** [comment]
@bitemyapp There already is a [license](https://github.com/sharkdp/cube-composer/blob/master/LICENSE). Do you mean that it should be added to the README?

**Comment by bitemyapp** [comment]
Whoa, I am blind, I scanned the file list and didn't see it.

Adding it to the README could be good, if only to spare others -_-'

Thanks y'all!
