### ISSUE TITLE
Level 4.1 solution not recognized

### ISSUE THREAD

**Issue by jonashw** [sharkdp/cube-composer#31]
From what I can tell, I met the goal on level 4.1 but the game does not recognize my solution.
My solution: [map(x2), map(+1), filter even, map(-1)]. See attached screenshot:

![cube_composer_bug_level_4 1](https://cloud.githubusercontent.com/assets/1964659/17867014/861e2df8-685d-11e6-9f93-e3eb2b36b769.png)

**Comment by jonashw** [comment]
It's worth noting that the solution above is not the optimal solution (there is a 2-function solution contained _within_ that solution) but it still meets the goal.

**Comment by sharkdp** [comment]
After `map (x2)` and `map (+1)`, every number is odd. Then, you apply `filter even`, which means you get the empty list. So this is not a solution (the 2-function solution that you mention, is a solution).

Unfortunately, the place holder for the empty list is not shown. I'll look into this.

**Comment by jonashw** [comment]
Ah, that makes sense.

**Comment by sharkdp** [comment]
Fixed! Thanks for reporting this.
