### ISSUE TITLE
How launch  cube-composer in our local environment,thanks

### ISSUE THREAD

**Issue by yepengxj** [sharkdp/cube-composer#38]
Hi,I'm new to nodejs. Could somebody kindly tell me how to start the game in my local environment after run those building process，thank you very much

**Comment by rosenk** [comment]
point your browser to the index.html file in the main project folder, example:
file:///home/rosen/home/dev/cube-composer/index.html

**Comment by sharkdp** [comment]
@yepengxj Did that work for you?

**Comment by yepengxj** [comment]
What if I run cube-composer in a docker container, I want to demonstrate how docker container works,before this I usually use 2048. Is that meanings I could use nginx to start cube-compose after build proecess. 
Thanks everybody

**Comment by rosenk** [comment]
@yepengxj It took me 5 min to realize you want to dockerize the game somehow. Yes, Nginx would work serving the game as a static website.

**Comment by yepengxj** [comment]
@rosenk Got it! Thanks you.
