### ISSUE TITLE
Click and drag doesn't work on Chrome or Firefox

### ISSUE THREAD

**Issue by bitwombat** [sharkdp/cube-composer#41]
Chrome 78.0.3904.97
Firefox 70.0.1
OS: Ubuntu 18.04

Expected behavior: 0.3 Goal states: "you can change the order of the functions by drag and drop." So, when I click and drag one function among several, in the right hand panel, it should go where I drop it.

Actual behavior: I get visual feeback that the function has been picked up - the image follows my mouse, but when I drop it, the image just disappears. The image of the function in the right panel does not move, either during dragging or after.

How to reproduce. Start from level 0.3 so that many functions are available. Click three in the left panel so that they appear in the right panel. Click and drag any one of them in the right panel and drop it in a new location, also within the right panel.

Other information: Clicking and dragging works for me in this test page: https://dunnbypaul.net/js_mouse/. I've also tried it in Chromium.

When empty, the right panels says "drop functions here". This also does not work.

Happy to provide other details. Really hoping this isn't my fault!

**Comment by bitwombat** [comment]
Also, seems to be the case with Chrome under Windows.

**Comment by sharkdp** [comment]
Thank you for reporting this!

I have updated the `Sortable` dependency which should hopefully fix this. It does so for me (also experienced the same error with a recent version of Firefox).
